export { defineConfig, loadConfig, resolveConfig, RULE_IDS, DEFAULT_WEIGHTS } from './config.js'
export type { DsDriftConfig, ResolvedConfig, RuleId } from './config.js'
export { loadTokens, classifyValue, lengthToPx } from './tokens/index.js'
export type { DesignToken, TokenKind } from './tokens/index.js'
export { run } from './engine.js'
export type { RunOptions, RunResult } from './engine.js'
export { computeScore } from './score.js'
export { buildJsonReport, renderJson, JSON_SCHEMA_VERSION } from './reporters/json.js'
export { renderGithub } from './reporters/github.js'
export { renderTerminal } from './reporters/terminal.js'
export type { Candidate, Finding, Rule, RuleContext } from './types.js'
